/** Local site imagery — Ethiopian coffee origin photography. */
export const SITE_IMAGES = {
  hero: "/images/ethiopian-highlands-origin.jpg",
  origin: "/images/coffee-nursery-shade.jpg",
  processing: "/images/coffee-cherries-drying-beds.jpg",
  quality: "/images/green-coffee-beans.jpg",
  farm: "/images/coffee-nursery-shade.jpg",
  drying: "/images/coffee-parchment-drying.jpg",
  harvest: "/images/coffee-farmers-harvest.jpg",
  export: "/images/coffee-sorting-export.jpg",
  washedStation: "/images/washed-coffee-station.jpg",
  washedBeans: "/images/washed-coffee-beans.jpg",
  greenBeans: "/images/green-coffee-beans.jpg",
  cherriesRipe: "/images/coffee-cherries-branch.jpg",
  cherriesHarvest: "/images/coffee-cherries-harvest-branch.jpg",
  cherriesDrying: "/images/coffee-cherries-sun-drying.jpg",
  cherriesMesh: "/images/coffee-cherries-mesh-drying.jpg",
  cherriesDryingBeds: "/images/coffee-cherries-drying-beds.jpg",
  seedlings: "/images/coffee-seedlings-closeup.jpg",
  nursery: "/images/coffee-nursery-shade.jpg",
  dryingCommunity: "/images/coffee-drying-community.jpg",
  dryingRaisedBeds: "/images/coffee-drying-raised-beds.jpg",
  parchmentDrying: "/images/coffee-parchment-drying.jpg",
  parchmentWorkers: "/images/coffee-parchment-workers.jpg",
  naturalDried: "/images/natural-coffee-dried-cherries.jpg",
  naturalBeds: "/images/natural-coffee-drying-beds.jpg",
  yirgacheffeHills: "/images/yirgacheffe-coffee-hills.jpg",
  cuppingOffice: "/images/coffee-cupping-office-lambek.jpg",
  cuppingSession: "/images/coffee-cupping-session.jpg",
  cuppingBuyers: "/images/coffee-cupping-buyers.jpg",
  cuppingLab: "/images/coffee-cupping-lab.jpg",
  teamPartners: "/images/lambek-team-partners.jpg",
  blogJourney: "/images/blog-coffee-journey.jpg",
  blogTradition: "/images/blog-ethiopian-tradition.jpg",
  placeholder: "/images/green-coffee-beans.jpg",
  logo: "/logos/logo-horizontal-darkgreen.png",
  logoDarkGreen: "/logos/logo-horizontal-darkgreen.png",
  logoWhite: "/logos/logo-horizontal-white.png",
  logoGold: "/logos/logo-horizontal-gold.png",
  logoBlack: "/logos/logo-horizontal-black.png",
  logoVerticalDarkGreen: "/logos/logo-vertical-darkgreen.png",
  logoVerticalWhite: "/logos/logo-vertical-white.png",
  logoVerticalGold: "/logos/logo-vertical-gold.png",
  logoCenteredDarkGreen: "/logos/logo-centered-darkgreen.png",
  logoCenteredWhite: "/logos/logo-centered-white.png",
  logoNameGold: "/logos/logo-name-gold.png",
  logoNameWhite: "/logos/logo-name-white.png",
  logoNameDarkGreen: "/logos/logo-name-darkgreen.png",
  emblem: "/logos/emblem-darkgreen.png",
  emblemDarkGreen: "/logos/emblem-darkgreen.png",
  emblemGold: "/logos/emblem-gold.png",
  emblemWhite: "/logos/emblem-white.png",
} as const;

export type SiteImageKey = keyof typeof SITE_IMAGES;

/** Homepage hero carousel slides showcasing nursery, cherries, drying & terroir */
export const HERO_SLIDES = [
  {
    type: "video" as const,
    videoSrc: "/videos/hero-lambek.mp4",
    src: SITE_IMAGES.hero,
    poster: SITE_IMAGES.hero,
    alt: "Lambek Coffee origin video - Ethiopian highland coffee production",
    tag: "Where Traditions Meet Aroma",
    title: "The Ethiopian Origin",
  },
  {
    type: "image" as const,
    src: SITE_IMAGES.nursery,
    alt: "Coffee seedling nursery under shade cloth in Ethiopian highlands",
    tag: "Nursery · Shade-Grown Start",
    title: "From Seedling To Cup",
  },
  {
    type: "image" as const,
    src: SITE_IMAGES.cuppingOffice,
    alt: "International buyers cupping Lambek Coffee samples in the tasting room",
    tag: "Cupping · Global Buyers",
    title: "Taste Of Ethiopian Coffee",
  },
  {
    type: "image" as const,
    src: SITE_IMAGES.teamPartners,
    alt: "Lambek Coffee team and international partners gathered at the Lambek showroom",
    tag: "Partners · Shared Craft",
    title: "Where Traditions Meet Aroma",
  },
  {
    type: "image" as const,
    src: SITE_IMAGES.cherriesDryingBeds,
    alt: "Ripe coffee cherries sun-drying on raised mesh beds",
    tag: "Natural Process · Raised Beds",
    title: "Sun-Dried Coffee Cherries",
  },
  {
    type: "image" as const,
    src: SITE_IMAGES.parchmentDrying,
    alt: "Parchment coffee beans drying on African raised beds with workers",
    tag: "Raised-Bed Slow Sun Drying",
    title: "Sun-Cured On African Beds",
  },
  {
    type: "image" as const,
    src: SITE_IMAGES.dryingCommunity,
    alt: "Community workers turning coffee on drying beds in Gedeo",
    tag: "Smallholder Farmers · Shared Work",
    title: "Tradition & Hand Work",
  },
  {
    type: "image" as const,
    src: SITE_IMAGES.quality,
    alt: "Specialty Grade 1 Ethiopian green coffee beans",
    tag: "Specialty Green Beans · Grade 1 & 2",
    title: "Pristine Green Coffee",
  },
] as const;

/** Gallery page curated images with comprehensive origin categories */
export const GALLERY_IMAGES = [
  {
    src: SITE_IMAGES.seedlings,
    alt: "Dense bed of young green coffee seedlings in nursery bags",
    category: "Nursery & Seedlings",
    description: "Healthy Arabica seedlings carefully raised before planting in highland farms.",
  },
  {
    src: SITE_IMAGES.nursery,
    alt: "Large coffee seedling nursery under protective shade-cloth canopy",
    category: "Nursery & Seedlings",
    description: "Shade-net nursery protecting young plants as they establish strong root systems.",
  },
  {
    src: SITE_IMAGES.cherriesRipe,
    alt: "Vibrant crimson coffee cherries ripening on heirloom Arabica branches",
    category: "Coffee Cherries",
    description: "Selective hand-picking ensures only fully ripe cherries at peak ripeness are harvested.",
  },
  {
    src: SITE_IMAGES.cherriesHarvest,
    alt: "Close-up of ripe red and purple coffee cherries on a farm branch",
    category: "Coffee Cherries",
    description: "Clusters of ripe cherries ready for selective harvest in Ethiopian agroforestry plots.",
  },
  {
    src: SITE_IMAGES.cherriesDryingBeds,
    alt: "Long beds of ripe red coffee cherries sun-drying on black mesh",
    category: "Natural Drying",
    description: "Natural process cherries spread thinly on raised mesh for even sun drying.",
  },
  {
    src: SITE_IMAGES.cherriesDrying,
    alt: "Elevated view of red coffee cherries drying across outdoor beds",
    category: "Natural Drying",
    description: "Wide drying lanes filled with freshly harvested cherries under bright highland sun.",
  },
  {
    src: SITE_IMAGES.cherriesMesh,
    alt: "Close-up of red coffee cherries drying on mesh with green leaf",
    category: "Natural Drying",
    description: "Glossy ripe cherries at the start of the natural drying process.",
  },
  {
    src: SITE_IMAGES.parchmentDrying,
    alt: "Parchment coffee beans drying on raised beds with farm workers",
    category: "Drying Beds",
    description: "Washed parchment turned regularly on African raised beds to reach ideal moisture.",
  },
  {
    src: SITE_IMAGES.parchmentWorkers,
    alt: "Workers in colorful clothing tending parchment coffee on drying beds",
    category: "Drying Beds",
    description: "Hands-on quality control as parchment coffee dries against forested hillsides.",
  },
  {
    src: SITE_IMAGES.dryingCommunity,
    alt: "Community members drying coffee cherries on raised bamboo beds",
    category: "Farms & Farmers",
    description: "Local farming communities working together across raised drying stations.",
  },
  {
    src: SITE_IMAGES.dryingRaisedBeds,
    alt: "Raised drying beds filled with dark coffee cherries in mountain landscape",
    category: "Farms & Farmers",
    description: "Traditional raised-bed drying stations set against lush Ethiopian highland forest.",
  },
  {
    src: SITE_IMAGES.quality,
    alt: "Raw, unroasted Ethiopian specialty green coffee beans",
    category: "Green Coffee Beans",
    description: "Jade-green, high-density Grade 1 Arabica beans prepared for specialty roasters worldwide.",
  },
  {
    src: SITE_IMAGES.washedStation,
    alt: "Washed coffee fermentation channels at an Ethiopian wet mill",
    category: "Washed Coffee Fermentation",
    description: "Washed fermentation and washing channels where mucilage is removed before drying.",
  },
  {
    src: SITE_IMAGES.export,
    alt: "Workers manually hand-sorting green coffee beans on inspection tables",
    category: "Hand Sorting Green Beans",
    description: "Careful hand-sorting removes defects before green coffee is prepared for export.",
  },
  {
    src: SITE_IMAGES.yirgacheffeHills,
    alt: "Lush forested Yirgacheffe coffee hills under blue highland sky",
    category: "Yirgacheffe Coffee Hills",
    description: "Characteristic Ethiopian highland terrain of the Yirgacheffe coffee-growing landscape.",
  },
] as const;

/** Tiny blur placeholder for next/image (warm neutral tone). */
export const IMAGE_BLUR =
  "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCwAA8A/9k=";
